development:
  adapter: "mysql"
  database: dbDev
  username: root
  password: root
  host: localhost

test:
  adapter: "mysql"
  database: dbTest
  username: root
  password: root
  host: localhost

production:
  adapter: "mysql"
  database: dbProd
  username: root
  password: root
  host: localhost
